### PR TITLE
feat(middleware): add denyList support

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
This PR introduces the denyList feature. It enables users to specify which API endoints or API endpoint methods should be ignore by this plugin.

### CODE REVIEW

**Comment by BabyDino** [comment]
@ComfortablyCoding Thanks for your continued work on your plugins. Any chance you can release this?

**Comment by Namstel** [comment]
@ComfortablyCoding This looks like something we desperately need. Is there an ETA on when this will be released? Thanks!

**Comment by ComfortablyCoding** [comment]
I will be reworking this due to #62, will try and release it tonight.

P.S. This next release will be a breaking/major version one.

**Comment by ComfortablyCoding** [comment]
This has been released in v3, see #64 for API change. Note if you are using the rest-cache plugin https://github.com/strapi-community/strapi-plugin-rest-cache/pull/46 needs to be merged before v3 will work with it

**Pull request merged**
